sudo: required
dist: trusty
language: node_js

script:
 - npm run build
 -  'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npx surge-github-autorelease -o wix -n wix-style-react -s $STORYBOOK_DIST -b $TRAVIS_BUILD_DIR -p $TRAVIS_PULL_REQUEST -t $GITHUB_API_TOKEN -d wix-wix-style-react; fi'

notifications:
  email:
    recipients:
      - fed-infra@wix.com
