sudo: required
dist: trusty
language: node_js

script:
 - npm run build
 - npm install surge
 - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/storybook-deploy.sh; fi'

notifications:
  email:
    recipients:
      - fed-infra@wix.com
