/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/testkits/unidriver.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
const load = module => {
  const MODULE_META_KEYS = ['__esModule'];

  const moduleFields = Object.keys(module).reduce((total, key) => {
    if (!MODULE_META_KEYS.includes(key)) {
      return total.concat(module[key]);
    }
    return total;
  }, []);

  let defaultOrFirstExport;
  if (module.default) {
    defaultOrFirstExport = module.default;
  } else if (moduleFields.length === 1) {
    defaultOrFirstExport = moduleFields[0];
  } else {
    defaultOrFirstExport = module;
  }
  return defaultOrFirstExport;
};


export const AccordionUniDriver = (load(require('../src/Accordion/Accordion.uni.driver')));
export const AddItemUniDriver = (load(require('../src/AddItem/AddItem.uni.driver')));
export const AddressInputUniDriver = (load(require('../src/AddressInput/AddressInput.uni.driver')));
export const AddressInputItemUniDriver = (load(require('../src/AddressInputItem/AddressInputItem.uni.driver')));
export const AnalyticsLayoutUniDriver = (load(require('../src/AnalyticsLayout/AnalyticsLayout.uni.driver')));
export const AnalyticsSummaryCardUniDriver = (load(require('../src/AnalyticsSummaryCard/AnalyticsSummaryCard.uni.driver')));
export const AnimateUniDriver = (load(require('../src/Animate/Animate.uni.driver')));
export const AnnouncementModalLayoutUniDriver = (load(require('../src/AnnouncementModalLayout/AnnouncementModalLayout.uni.driver')));
export const AreaChartUniDriver = (load(require('../src/AreaChart/AreaChart.uni.driver')));
export const AtlasAddressInputUniDriver = (load(require('../src/AtlasAddressInput/AtlasAddressInput.uni.driver')));
export const AudioPlayerUniDriver = (load(require('../src/AudioPlayer/AudioPlayer.uni.driver')));
export const AutoCompleteUniDriver = (load(require('../src/AutoComplete/AutoComplete.uni.driver')));
export const AutoCompleteWithLabelUniDriver = (load(require('../src/AutoCompleteWithLabel/AutoCompleteWithLabel.uni.driver')));
export const AvatarUniDriver = (load(require('../src/Avatar/Avatar.uni.driver')));
export const AvatarGroupUniDriver = (load(require('../src/AvatarGroup/AvatarGroup.uni.driver')));
export const BadgeUniDriver = (load(require('../src/Badge/Badge.uni.driver')));
export const BadgeSelectUniDriver = (load(require('../src/BadgeSelect/BadgeSelect.uni.driver')));
export const BadgeSelectItemUniDriver = (load(require('../src/BadgeSelectItem/BadgeSelectItem.uni.driver')));
export const BarChartUniDriver = (load(require('../src/BarChart/BarChart.uni.driver')));
export const BounceAnimationUniDriver = (load(require('../src/BounceAnimation/BounceAnimation.uni.driver')));
export const BoxUniDriver = (load(require('../src/Box/Box.uni.driver')));
export const BreadcrumbsUniDriver = (load(require('../src/Breadcrumbs/Breadcrumbs.uni.driver')));
export const BrowserPreviewWidgetUniDriver = (load(require('../src/BrowserPreviewWidget/BrowserPreviewWidget.uni.driver')));
export const ButtonUniDriver = (load(require('../src/Button/Button.uni.driver')));
export const CalendarUniDriver = (load(require('../src/Calendar/Calendar.uni.driver')));
export const CalendarPanelUniDriver = (load(require('../src/CalendarPanel/CalendarPanel.uni.driver')));
export const CalendarPanelFooterUniDriver = (load(require('../src/CalendarPanelFooter/CalendarPanelFooter.uni.driver')));
export const CardFolderTabsUniDriver = (load(require('../src/CardFolderTabs/CardFolderTabs.uni.driver')));
export const CardGalleryItemUniDriver = (load(require('../src/CardGalleryItem/CardGalleryItem.uni.driver')));
export const CarouselUniDriver = (load(require('../src/Carousel/Carousel.uni.driver')));
export const CarouselWIPUniDriver = (load(require('../src/CarouselWIP/CarouselWIP.uni.driver')));
export const CheckToggleUniDriver = (load(require('../src/CheckToggle/CheckToggle.uni.driver')));
export const CheckboxUniDriver = (load(require('../src/Checkbox/Checkbox.uni.driver')));
export const CircularProgressBarUniDriver = (load(require('../src/CircularProgressBar/CircularProgressBar.uni.driver')));
export const CloseButtonUniDriver = (load(require('../src/CloseButton/CloseButton.uni.driver')));
export const ColorInputUniDriver = (load(require('../src/ColorInput/ColorInput.uni.driver')));
export const ColorPickerUniDriver = (load(require('../src/ColorPicker/ColorPicker.uni.driver')));
export const ComposerHeaderUniDriver = (load(require('../src/ComposerHeader/ComposerHeader.uni.driver')));
export const ComposerSidebarUniDriver = (load(require('../src/ComposerSidebar/ComposerSidebar.uni.driver')));
export const ContactItemBuilderUniDriver = (load(require('../src/ContactItemBuilder/ContactItemBuilder.uni.driver')));
export const CopyClipboardUniDriver = (load(require('../src/CopyClipboard/CopyClipboard.uni.driver')));
export const CounterBadgeUniDriver = (load(require('../src/CounterBadge/CounterBadge.uni.driver')));
export const CustomModalLayoutUniDriver = (load(require('../src/CustomModalLayout/CustomModalLayout.uni.driver')));
export const DatePickerUniDriver = (load(require('../src/DatePicker/DatePicker.uni.driver')));
export const DividerUniDriver = (load(require('../src/Divider/Divider.uni.driver')));
export const DropdownUniDriver = (load(require('../src/Dropdown/Dropdown.uni.driver')));
export const DropdownBaseUniDriver = (load(require('../src/DropdownBase/DropdownBase.uni.driver')));
export const DropdownLayoutUniDriver = (load(require('../src/DropdownLayout/DropdownLayout.uni.driver')));
export const DropzoneUniDriver = (load(require('../src/Dropzone/Dropzone.uni.driver')));
export const EditableSelectorUniDriver = (load(require('../src/EditableSelector/EditableSelector.uni.driver')));
export const EditableTitleUniDriver = (load(require('../src/EditableTitle/EditableTitle.uni.driver')));
export const EmptyStateUniDriver = (load(require('../src/EmptyState/EmptyState.uni.driver')));
export const FacesRatingBarUniDriver = (load(require('../src/FacesRatingBar/FacesRatingBar.uni.driver')));
export const FeatureListUniDriver = (load(require('../src/FeatureList/FeatureList.uni.driver')));
export const FilePickerUniDriver = (load(require('../src/FilePicker/FilePicker.uni.driver')));
export const FileUploadUniDriver = (load(require('../src/FileUpload/FileUpload.uni.driver')));
export const FillButtonUniDriver = (load(require('../src/FillButton/FillButton.uni.driver')));
export const FillPreviewUniDriver = (load(require('../src/FillPreview/FillPreview.uni.driver')));
export const FloatingHelperUniDriver = (load(require('../src/FloatingHelper/FloatingHelper.uni.driver')));
export const FloatingNotificationUniDriver = (load(require('../src/FloatingNotification/FloatingNotification.uni.driver')));
export const FontUpgradeUniDriver = (load(require('../src/FontUpgrade/FontUpgrade.uni.driver')));
export const FormFieldUniDriver = (load(require('../src/FormField/FormField.uni.driver')));
export const FunnelChartUniDriver = (load(require('../src/FunnelChart/FunnelChart.uni.driver')));
export const GenericModalLayoutUniDriver = (load(require('../src/GenericModalLayout/GenericModalLayout.uni.driver')));
export const GooglePreviewUniDriver = (load(require('../src/GooglePreview/GooglePreview.uni.driver')));
export const HeadingUniDriver = (load(require('../src/Heading/Heading.uni.driver')));
export const HighlighterUniDriver = (load(require('../src/Highlighter/Highlighter.uni.driver')));
export const HorizontalTimelineUniDriver = (load(require('../src/HorizontalTimeline/HorizontalTimeline.uni.driver')));
export const IconButtonUniDriver = (load(require('../src/IconButton/IconButton.uni.driver')));
export const ImageUniDriver = (load(require('../src/Image/Image.uni.driver')));
export const ImageViewerUniDriver = (load(require('../src/ImageViewer/ImageViewer.uni.driver')));
export const InfoIconUniDriver = (load(require('../src/InfoIcon/InfoIcon.uni.driver')));
export const InputUniDriver = (load(require('../src/Input/Input.uni.driver')));
export const InputAreaUniDriver = (load(require('../src/InputArea/InputArea.uni.driver')));
export const InputWithLabelUniDriver = (load(require('../src/InputWithLabel/InputWithLabel.uni.driver')));
export const InputWithOptionsUniDriver = (load(require('../src/InputWithOptions/InputWithOptions.uni.driver')));
export const LabelledElementUniDriver = (load(require('../src/LabelledElement/LabelledElement.uni.driver')));
export const LinearProgressBarUniDriver = (load(require('../src/LinearProgressBar/LinearProgressBar.uni.driver')));
export const ListItemActionUniDriver = (load(require('../src/ListItemAction/ListItemAction.uni.driver')));
export const ListItemEditableUniDriver = (load(require('../src/ListItemEditable/ListItemEditable.uni.driver')));
export const ListItemSectionUniDriver = (load(require('../src/ListItemSection/ListItemSection.uni.driver')));
export const ListItemSelectUniDriver = (load(require('../src/ListItemSelect/ListItemSelect.uni.driver')));
export const LoaderUniDriver = (load(require('../src/Loader/Loader.uni.driver')));
export const MarketingLayoutUniDriver = (load(require('../src/MarketingLayout/MarketingLayout.uni.driver')));
export const MarketingPageLayoutUniDriver = (load(require('../src/MarketingPageLayout/MarketingPageLayout.uni.driver')));
export const MarketingPageLayoutContentUniDriver = (load(require('../src/MarketingPageLayoutContent/MarketingPageLayoutContent.uni.driver')));
export const MediaOverlayUniDriver = (load(require('../src/MediaOverlay/MediaOverlay.uni.driver')));
export const MessageModalLayoutUniDriver = (load(require('../src/MessageModalLayout/MessageModalLayout.uni.driver')));
export const MobilePreviewWidgetUniDriver = (load(require('../src/MobilePreviewWidget/MobilePreviewWidget.uni.driver')));
export const ModalUniDriver = (load(require('../src/Modal/Modal.uni.driver')));
export const ModalMobileLayoutUniDriver = (load(require('../src/ModalMobileLayout/ModalMobileLayout.uni.driver')));
export const ModalPreviewLayoutUniDriver = (load(require('../src/ModalPreviewLayout/ModalPreviewLayout.uni.driver')));
export const ModalSelectorLayoutUniDriver = (load(require('../src/ModalSelectorLayout/ModalSelectorLayout.uni.driver')));
export const MultiSelectUniDriver = (load(require('../src/MultiSelect/MultiSelect.uni.driver')));
export const MultiSelectCheckboxUniDriver = (load(require('../src/MultiSelectCheckbox/MultiSelectCheckbox.uni.driver')));
export const NoBorderInputUniDriver = (load(require('../src/NoBorderInput/NoBorderInput.uni.driver')));
export const NotificationUniDriver = (load(require('../src/Notification/Notification.uni.driver')));
export const NumberInputUniDriver = (load(require('../src/NumberInput/NumberInput.uni.driver')));
export const PageUniDriver = (load(require('../src/Page/Page.uni.driver')));
export const PageFooterUniDriver = (load(require('../src/PageFooter/PageFooter.uni.driver')));
export const PageHeaderUniDriver = (load(require('../src/PageHeader/PageHeader.uni.driver')));
export const PageSectionUniDriver = (load(require('../src/PageSection/PageSection.uni.driver')));
export const PaginationUniDriver = (load(require('../src/Pagination/Pagination.uni.driver')));
export const PaletteUniDriver = (load(require('../src/Palette/Palette.uni.driver')));
export const PopoverUniDriver = (load(require('../src/Popover/Popover.uni.driver')));
export const PopoverMenuUniDriver = (load(require('../src/PopoverMenu/PopoverMenu.uni.driver')));
export const PreviewWidgetUniDriver = (load(require('../src/PreviewWidget/PreviewWidget.uni.driver')));
export const ProportionUniDriver = (load(require('../src/Proportion/Proportion.uni.driver')));
export const PulseAnimationUniDriver = (load(require('../src/PulseAnimation/PulseAnimation.uni.driver')));
export const RadioUniDriver = (load(require('../src/Radio/Radio.uni.driver')));
export const RadioGroupUniDriver = (load(require('../src/RadioGroup/RadioGroup.uni.driver')));
export const RangeUniDriver = (load(require('../src/Range/Range.uni.driver')));
export const RichTextInputAreaUniDriver = (load(require('../src/RichTextInputArea/RichTextInputArea.uni.driver')));
export const SearchUniDriver = (load(require('../src/Search/Search.uni.driver')));
export const SectionHelperUniDriver = (load(require('../src/SectionHelper/SectionHelper.uni.driver')));
export const SegmentedToggleUniDriver = (load(require('../src/SegmentedToggle/SegmentedToggle.uni.driver')));
export const SelectableAccordionUniDriver = (load(require('../src/SelectableAccordion/SelectableAccordion.uni.driver')));
export const SelectorUniDriver = (load(require('../src/Selector/Selector.uni.driver')));
export const SelectorListUniDriver = (load(require('../src/SelectorList/SelectorList.uni.driver')));
export const SidePanelUniDriver = (load(require('../src/SidePanel/SidePanel.uni.driver')));
export const SidebarUniDriver = (load(require('../src/Sidebar/Sidebar.uni.driver')));
export const SidebarBackButtonUniDriver = (load(require('../src/SidebarBackButton/SidebarBackButton.uni.driver')));
export const SidebarDividerUniDriver = (load(require('../src/SidebarDivider/SidebarDivider.uni.driver')));
export const SidebarHeaderUniDriver = (load(require('../src/SidebarHeader/SidebarHeader.uni.driver')));
export const SidebarSectionItemUniDriver = (load(require('../src/SidebarSectionItem/SidebarSectionItem.uni.driver')));
export const SidebarSectionTitleUniDriver = (load(require('../src/SidebarSectionTitle/SidebarSectionTitle.uni.driver')));
export const SkeletonUniDriver = (load(require('../src/Skeleton/Skeleton.uni.driver')));
export const SkeletonCircleUniDriver = (load(require('../src/SkeletonCircle/SkeletonCircle.uni.driver')));
export const SkeletonGroupUniDriver = (load(require('../src/SkeletonGroup/SkeletonGroup.uni.driver')));
export const SkeletonLineUniDriver = (load(require('../src/SkeletonLine/SkeletonLine.uni.driver')));
export const SkeletonRectangleUniDriver = (load(require('../src/SkeletonRectangle/SkeletonRectangle.uni.driver')));
export const SliderUniDriver = (load(require('../src/Slider/Slider.uni.driver')));
export const SocialButtonUniDriver = (load(require('../src/SocialButton/SocialButton.uni.driver')));
export const SocialPreviewUniDriver = (load(require('../src/SocialPreview/SocialPreview.uni.driver')));
export const SortableGridUniDriver = (load(require('../src/SortableGrid/SortableGrid.uni.driver')));
export const SparklineChartUniDriver = (load(require('../src/SparklineChart/SparklineChart.uni.driver')));
export const StackedBarChartUniDriver = (load(require('../src/StackedBarChart/StackedBarChart.uni.driver')));
export const StarsRatingBarUniDriver = (load(require('../src/StarsRatingBar/StarsRatingBar.uni.driver')));
export const StatisticsWidgetUniDriver = (load(require('../src/StatisticsWidget/StatisticsWidget.uni.driver')));
export const StatusIndicatorUniDriver = (load(require('../src/StatusIndicator/StatusIndicator.uni.driver')));
export const StepperUniDriver = (load(require('../src/Stepper/Stepper.uni.driver')));
export const StyledNestableListUniDriver = (load(require('../src/StyledNestableList/StyledNestableList.uni.driver')));
export const SwatchesUniDriver = (load(require('../src/Swatches/Swatches.uni.driver')));
export const TableUniDriver = (load(require('../src/Table/Table.uni.driver')));
export const TableActionCellUniDriver = (load(require('../src/TableActionCell/TableActionCell.uni.driver')));
export const TableListItemUniDriver = (load(require('../src/TableListItem/TableListItem.uni.driver')));
export const TabsUniDriver = (load(require('../src/Tabs/Tabs.uni.driver')));
export const TagUniDriver = (load(require('../src/Tag/Tag.uni.driver')));
export const TagListUniDriver = (load(require('../src/TagList/TagList.uni.driver')));
export const TestimonialListUniDriver = (load(require('../src/TestimonialList/TestimonialList.uni.driver')));
export const TextUniDriver = (load(require('../src/Text/Text.uni.driver')));
export const TextButtonUniDriver = (load(require('../src/TextButton/TextButton.uni.driver')));
export const ThumbnailUniDriver = (load(require('../src/Thumbnail/Thumbnail.uni.driver')));
export const TimeInputUniDriver = (load(require('../src/TimeInput/TimeInput.uni.driver')));
export const TimeInputWipUniDriver = (load(require('../src/TimeInputWip/TimeInputWip.uni.driver')));
export const TimeTableUniDriver = (load(require('../src/TimeTable/TimeTable.uni.driver')));
export const TimelineUniDriver = (load(require('../src/Timeline/Timeline.uni.driver')));
export const ToggleButtonUniDriver = (load(require('../src/ToggleButton/ToggleButton.uni.driver')));
export const ToggleSwitchUniDriver = (load(require('../src/ToggleSwitch/ToggleSwitch.uni.driver')));
export const TooltipUniDriver = (load(require('../src/Tooltip/Tooltip.uni.driver')));
export const TrendIndicatorUniDriver = (load(require('../src/TrendIndicator/TrendIndicator.uni.driver')));
export const VariableInputUniDriver = (load(require('../src/VariableInput/VariableInput.uni.driver')));
export const VerticalTabsUniDriver = (load(require('../src/VerticalTabs/VerticalTabs.uni.driver')));
export const VerticalTabsItemUniDriver = (load(require('../src/VerticalTabsItem/VerticalTabsItem.uni.driver')));
export const WixStyleReactProviderUniDriver = (load(require('../src/WixStyleReactProvider/WixStyleReactProvider.uni.driver')));
export const CardHeaderUniDriver = (load(require('../src/Card/Header/Header.uni.driver')));
export const EditableRowUniDriver = (load(require('../src/EditableSelector/EditableRow/EditableRow.uni.driver')));
export const RadioButtonUniDriver = (load(require('../src/RadioGroup/RadioButton/RadioButton.uni.driver')));
export const MessageBoxMarketerialLayoutUniDriver = (load(require('../src/MessageBox/MarketerialLayout/MessageBoxMarketerialLayout.uni.driver')));
export const MessageBoxFunctionalLayoutUniDriver = (load(require('../src/MessageBox/FunctionalLayout/MessageBoxFunctionalLayout.uni.driver')));
export const CardSubheaderUniDriver = (load(require('../src/Card/Subheader/Subheader.uni.driver')));
